name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy Say it again
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "johannessch-neues2020-54"
          entrypoint: "main.ts"
          root: "."
          env: |
            R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
            R2_ENDPOINT=${{ secrets.R2_ENDPOINT }}
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
<<<<<<< HEAD
            SUBDOMAIN=${{ secrets.SUBDOMAIN }}
=======
            SUBDOMAIN=${{ secrets.SUBDOMAIN }}
>>>>>>> 1a04364a977dcdafb300e7291a5ea716354c2b8f
